# Site settings
title: I'm nobody
description: 'Read, learn and write your code'
url: 'http://haivx.github.io'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Hai Xuan Vo'
  email: haivx0206@gmail.com
  twitter_username: haivx0206
  facebook_username: haixuan
  github_username:  haixuan
  linkedin_username:  hai-vo-b265ab134/

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
excerpt_separator: "<!-- more -->"
